# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d42a9e6ca4769d1e74949b0111c96a81c83c6e0559c3009e77f26366fbc054fd33cf8ef01c624e540efc0005542c0bf5c9c1a983600ea6376c80b4f3c02d1808

test:
  secret_key_base: 1aaf7d3bff7d877953939abab9906792ecac7302cfb3298937338786e39e4943975963df201727236774e7d289ed2cd220f9efe63a074a9b3cd2d411a01a3162

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
